// Generated by CoffeeScript 1.6.2
(function() {
  map.create2DView = function(shapes) {
    var shape, st, states, _i, _len, _ref;

    states = {};
    _ref = shapes[0];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      shape = _ref[_i];
      st = new map.State2D(shape);
      states[shape.attributes.statename.value] = st;
    }
    return map.states = states;
  };

}).call(this);
