// Generated by CoffeeScript 1.6.2
(function() {
  map.sendTweet = function(team) {
    var locFail, locSuccess;

    locSuccess = function(loc) {
      var locGeoJson, state, text, _i, _len, _ref;

      locGeoJson = {
        type: "Point",
        coordinates: [loc.coords.longitude, loc.coords.latitude]
      };
      _ref = map.stateShapes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        state = _ref[_i];
        if (gju.pointInPolygon(locGeoJson, state.geometry)) {
          console.log(state);
          text = "I'm claiming " + state.properties.STATE_NAME + " as " + team + " territory on www.thetweetometer.com!";
          window.location = "https://twitter.com/intent/tweet?text=" + text + "&via=_alastair";
          break;
        }
      }
      return console.log("wuuh");
    };
    locFail = function() {
      $("#locating").hide();
      $("#mapholder").css("visibility", "");
      return alert("Couldn't find your location!");
    };
    $("#locating").show();
    $("#mapholder").css("visibility", "hidden");
    return navigator.geolocation.getCurrentPosition(locSuccess, locFail);
  };

}).call(this);
